module.exports = [
  {
    login: 'tinomen',
    id: 4095,
    node_id: 'MDQ6VXNlcjQwOTU=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/4095?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tinomen',
    html_url: 'https://github.com/tinomen',
    followers_url: 'https://api.github.com/users/tinomen/followers',
    following_url:
      'https://api.github.com/users/tinomen/following{/other_user}',
    gists_url: 'https://api.github.com/users/tinomen/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tinomen/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tinomen/subscriptions',
    organizations_url: 'https://api.github.com/users/tinomen/orgs',
    repos_url: 'https://api.github.com/users/tinomen/repos',
    events_url: 'https://api.github.com/users/tinomen/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tinomen/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'jessmartin',
    id: 27258,
    node_id: 'MDQ6VXNlcjI3MjU4',
    avatar_url: 'https://avatars2.githubusercontent.com/u/27258?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jessmartin',
    html_url: 'https://github.com/jessmartin',
    followers_url: 'https://api.github.com/users/jessmartin/followers',
    following_url:
      'https://api.github.com/users/jessmartin/following{/other_user}',
    gists_url: 'https://api.github.com/users/jessmartin/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jessmartin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jessmartin/subscriptions',
    organizations_url: 'https://api.github.com/users/jessmartin/orgs',
    repos_url: 'https://api.github.com/users/jessmartin/repos',
    events_url: 'https://api.github.com/users/jessmartin/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jessmartin/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'amcgee',
    id: 947888,
    node_id: 'MDQ6VXNlcjk0Nzg4OA==',
    avatar_url: 'https://avatars3.githubusercontent.com/u/947888?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/amcgee',
    html_url: 'https://github.com/amcgee',
    followers_url: 'https://api.github.com/users/amcgee/followers',
    following_url: 'https://api.github.com/users/amcgee/following{/other_user}',
    gists_url: 'https://api.github.com/users/amcgee/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/amcgee/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/amcgee/subscriptions',
    organizations_url: 'https://api.github.com/users/amcgee/orgs',
    repos_url: 'https://api.github.com/users/amcgee/repos',
    events_url: 'https://api.github.com/users/amcgee/events{/privacy}',
    received_events_url: 'https://api.github.com/users/amcgee/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'berniedurfee',
    id: 6180274,
    node_id: 'MDQ6VXNlcjYxODAyNzQ=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/6180274?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/berniedurfee',
    html_url: 'https://github.com/berniedurfee',
    followers_url: 'https://api.github.com/users/berniedurfee/followers',
    following_url:
      'https://api.github.com/users/berniedurfee/following{/other_user}',
    gists_url: 'https://api.github.com/users/berniedurfee/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/berniedurfee/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/berniedurfee/subscriptions',
    organizations_url: 'https://api.github.com/users/berniedurfee/orgs',
    repos_url: 'https://api.github.com/users/berniedurfee/repos',
    events_url: 'https://api.github.com/users/berniedurfee/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/berniedurfee/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'LeTanque',
    id: 7180772,
    node_id: 'MDQ6VXNlcjcxODA3NzI=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/7180772?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/LeTanque',
    html_url: 'https://github.com/LeTanque',
    followers_url: 'https://api.github.com/users/LeTanque/followers',
    following_url:
      'https://api.github.com/users/LeTanque/following{/other_user}',
    gists_url: 'https://api.github.com/users/LeTanque/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/LeTanque/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/LeTanque/subscriptions',
    organizations_url: 'https://api.github.com/users/LeTanque/orgs',
    repos_url: 'https://api.github.com/users/LeTanque/repos',
    events_url: 'https://api.github.com/users/LeTanque/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/LeTanque/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'mcgowent',
    id: 7843803,
    node_id: 'MDQ6VXNlcjc4NDM4MDM=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/7843803?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mcgowent',
    html_url: 'https://github.com/mcgowent',
    followers_url: 'https://api.github.com/users/mcgowent/followers',
    following_url:
      'https://api.github.com/users/mcgowent/following{/other_user}',
    gists_url: 'https://api.github.com/users/mcgowent/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mcgowent/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mcgowent/subscriptions',
    organizations_url: 'https://api.github.com/users/mcgowent/orgs',
    repos_url: 'https://api.github.com/users/mcgowent/repos',
    events_url: 'https://api.github.com/users/mcgowent/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mcgowent/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'ryan-hamblin',
    id: 8798259,
    node_id: 'MDQ6VXNlcjg3OTgyNTk=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/8798259?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ryan-hamblin',
    html_url: 'https://github.com/ryan-hamblin',
    followers_url: 'https://api.github.com/users/ryan-hamblin/followers',
    following_url:
      'https://api.github.com/users/ryan-hamblin/following{/other_user}',
    gists_url: 'https://api.github.com/users/ryan-hamblin/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ryan-hamblin/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/ryan-hamblin/subscriptions',
    organizations_url: 'https://api.github.com/users/ryan-hamblin/orgs',
    repos_url: 'https://api.github.com/users/ryan-hamblin/repos',
    events_url: 'https://api.github.com/users/ryan-hamblin/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ryan-hamblin/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'jeremiahtenbrink',
    id: 17443353,
    node_id: 'MDQ6VXNlcjE3NDQzMzUz',
    avatar_url: 'https://avatars3.githubusercontent.com/u/17443353?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jeremiahtenbrink',
    html_url: 'https://github.com/jeremiahtenbrink',
    followers_url: 'https://api.github.com/users/jeremiahtenbrink/followers',
    following_url:
      'https://api.github.com/users/jeremiahtenbrink/following{/other_user}',
    gists_url: 'https://api.github.com/users/jeremiahtenbrink/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jeremiahtenbrink/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/jeremiahtenbrink/subscriptions',
    organizations_url: 'https://api.github.com/users/jeremiahtenbrink/orgs',
    repos_url: 'https://api.github.com/users/jeremiahtenbrink/repos',
    events_url:
      'https://api.github.com/users/jeremiahtenbrink/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jeremiahtenbrink/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'ccurry20',
    id: 19153270,
    node_id: 'MDQ6VXNlcjE5MTUzMjcw',
    avatar_url: 'https://avatars1.githubusercontent.com/u/19153270?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ccurry20',
    html_url: 'https://github.com/ccurry20',
    followers_url: 'https://api.github.com/users/ccurry20/followers',
    following_url:
      'https://api.github.com/users/ccurry20/following{/other_user}',
    gists_url: 'https://api.github.com/users/ccurry20/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ccurry20/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ccurry20/subscriptions',
    organizations_url: 'https://api.github.com/users/ccurry20/orgs',
    repos_url: 'https://api.github.com/users/ccurry20/repos',
    events_url: 'https://api.github.com/users/ccurry20/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ccurry20/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'gmgower',
    id: 20153709,
    node_id: 'MDQ6VXNlcjIwMTUzNzA5',
    avatar_url: 'https://avatars2.githubusercontent.com/u/20153709?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gmgower',
    html_url: 'https://github.com/gmgower',
    followers_url: 'https://api.github.com/users/gmgower/followers',
    following_url:
      'https://api.github.com/users/gmgower/following{/other_user}',
    gists_url: 'https://api.github.com/users/gmgower/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gmgower/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gmgower/subscriptions',
    organizations_url: 'https://api.github.com/users/gmgower/orgs',
    repos_url: 'https://api.github.com/users/gmgower/repos',
    events_url: 'https://api.github.com/users/gmgower/events{/privacy}',
    received_events_url: 'https://api.github.com/users/gmgower/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: '1ouie',
    id: 23627772,
    node_id: 'MDQ6VXNlcjIzNjI3Nzcy',
    avatar_url: 'https://avatars0.githubusercontent.com/u/23627772?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/1ouie',
    html_url: 'https://github.com/1ouie',
    followers_url: 'https://api.github.com/users/1ouie/followers',
    following_url: 'https://api.github.com/users/1ouie/following{/other_user}',
    gists_url: 'https://api.github.com/users/1ouie/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/1ouie/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/1ouie/subscriptions',
    organizations_url: 'https://api.github.com/users/1ouie/orgs',
    repos_url: 'https://api.github.com/users/1ouie/repos',
    events_url: 'https://api.github.com/users/1ouie/events{/privacy}',
    received_events_url: 'https://api.github.com/users/1ouie/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'partyshah',
    id: 25253905,
    node_id: 'MDQ6VXNlcjI1MjUzOTA1',
    avatar_url: 'https://avatars3.githubusercontent.com/u/25253905?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/partyshah',
    html_url: 'https://github.com/partyshah',
    followers_url: 'https://api.github.com/users/partyshah/followers',
    following_url:
      'https://api.github.com/users/partyshah/following{/other_user}',
    gists_url: 'https://api.github.com/users/partyshah/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/partyshah/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/partyshah/subscriptions',
    organizations_url: 'https://api.github.com/users/partyshah/orgs',
    repos_url: 'https://api.github.com/users/partyshah/repos',
    events_url: 'https://api.github.com/users/partyshah/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/partyshah/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'meganfontenot',
    id: 33911508,
    node_id: 'MDQ6VXNlcjMzOTExNTA4',
    avatar_url: 'https://avatars0.githubusercontent.com/u/33911508?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/meganfontenot',
    html_url: 'https://github.com/meganfontenot',
    followers_url: 'https://api.github.com/users/meganfontenot/followers',
    following_url:
      'https://api.github.com/users/meganfontenot/following{/other_user}',
    gists_url: 'https://api.github.com/users/meganfontenot/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/meganfontenot/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/meganfontenot/subscriptions',
    organizations_url: 'https://api.github.com/users/meganfontenot/orgs',
    repos_url: 'https://api.github.com/users/meganfontenot/repos',
    events_url: 'https://api.github.com/users/meganfontenot/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/meganfontenot/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'droneal11015',
    id: 41247530,
    node_id: 'MDQ6VXNlcjQxMjQ3NTMw',
    avatar_url: 'https://avatars2.githubusercontent.com/u/41247530?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/droneal11015',
    html_url: 'https://github.com/droneal11015',
    followers_url: 'https://api.github.com/users/droneal11015/followers',
    following_url:
      'https://api.github.com/users/droneal11015/following{/other_user}',
    gists_url: 'https://api.github.com/users/droneal11015/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/droneal11015/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/droneal11015/subscriptions',
    organizations_url: 'https://api.github.com/users/droneal11015/orgs',
    repos_url: 'https://api.github.com/users/droneal11015/repos',
    events_url: 'https://api.github.com/users/droneal11015/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/droneal11015/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'Trip4077',
    id: 41757264,
    node_id: 'MDQ6VXNlcjQxNzU3MjY0',
    avatar_url: 'https://avatars0.githubusercontent.com/u/41757264?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Trip4077',
    html_url: 'https://github.com/Trip4077',
    followers_url: 'https://api.github.com/users/Trip4077/followers',
    following_url:
      'https://api.github.com/users/Trip4077/following{/other_user}',
    gists_url: 'https://api.github.com/users/Trip4077/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Trip4077/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Trip4077/subscriptions',
    organizations_url: 'https://api.github.com/users/Trip4077/orgs',
    repos_url: 'https://api.github.com/users/Trip4077/repos',
    events_url: 'https://api.github.com/users/Trip4077/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Trip4077/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'MAmaya1',
    id: 42827064,
    node_id: 'MDQ6VXNlcjQyODI3MDY0',
    avatar_url: 'https://avatars0.githubusercontent.com/u/42827064?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MAmaya1',
    html_url: 'https://github.com/MAmaya1',
    followers_url: 'https://api.github.com/users/MAmaya1/followers',
    following_url:
      'https://api.github.com/users/MAmaya1/following{/other_user}',
    gists_url: 'https://api.github.com/users/MAmaya1/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/MAmaya1/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/MAmaya1/subscriptions',
    organizations_url: 'https://api.github.com/users/MAmaya1/orgs',
    repos_url: 'https://api.github.com/users/MAmaya1/repos',
    events_url: 'https://api.github.com/users/MAmaya1/events{/privacy}',
    received_events_url: 'https://api.github.com/users/MAmaya1/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'Levi-Huynh',
    id: 43801393,
    node_id: 'MDQ6VXNlcjQzODAxMzkz',
    avatar_url: 'https://avatars1.githubusercontent.com/u/43801393?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Levi-Huynh',
    html_url: 'https://github.com/Levi-Huynh',
    followers_url: 'https://api.github.com/users/Levi-Huynh/followers',
    following_url:
      'https://api.github.com/users/Levi-Huynh/following{/other_user}',
    gists_url: 'https://api.github.com/users/Levi-Huynh/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Levi-Huynh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Levi-Huynh/subscriptions',
    organizations_url: 'https://api.github.com/users/Levi-Huynh/orgs',
    repos_url: 'https://api.github.com/users/Levi-Huynh/repos',
    events_url: 'https://api.github.com/users/Levi-Huynh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Levi-Huynh/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'RonnySAlvarado',
    id: 45113320,
    node_id: 'MDQ6VXNlcjQ1MTEzMzIw',
    avatar_url: 'https://avatars1.githubusercontent.com/u/45113320?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/RonnySAlvarado',
    html_url: 'https://github.com/RonnySAlvarado',
    followers_url: 'https://api.github.com/users/RonnySAlvarado/followers',
    following_url:
      'https://api.github.com/users/RonnySAlvarado/following{/other_user}',
    gists_url: 'https://api.github.com/users/RonnySAlvarado/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/RonnySAlvarado/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/RonnySAlvarado/subscriptions',
    organizations_url: 'https://api.github.com/users/RonnySAlvarado/orgs',
    repos_url: 'https://api.github.com/users/RonnySAlvarado/repos',
    events_url: 'https://api.github.com/users/RonnySAlvarado/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/RonnySAlvarado/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'dswhitely1',
    id: 45896739,
    node_id: 'MDQ6VXNlcjQ1ODk2NzM5',
    avatar_url: 'https://avatars0.githubusercontent.com/u/45896739?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dswhitely1',
    html_url: 'https://github.com/dswhitely1',
    followers_url: 'https://api.github.com/users/dswhitely1/followers',
    following_url:
      'https://api.github.com/users/dswhitely1/following{/other_user}',
    gists_url: 'https://api.github.com/users/dswhitely1/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/dswhitely1/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dswhitely1/subscriptions',
    organizations_url: 'https://api.github.com/users/dswhitely1/orgs',
    repos_url: 'https://api.github.com/users/dswhitely1/repos',
    events_url: 'https://api.github.com/users/dswhitely1/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/dswhitely1/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'austinbro5',
    id: 47146701,
    node_id: 'MDQ6VXNlcjQ3MTQ2NzAx',
    avatar_url: 'https://avatars3.githubusercontent.com/u/47146701?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/austinbro5',
    html_url: 'https://github.com/austinbro5',
    followers_url: 'https://api.github.com/users/austinbro5/followers',
    following_url:
      'https://api.github.com/users/austinbro5/following{/other_user}',
    gists_url: 'https://api.github.com/users/austinbro5/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/austinbro5/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/austinbro5/subscriptions',
    organizations_url: 'https://api.github.com/users/austinbro5/orgs',
    repos_url: 'https://api.github.com/users/austinbro5/repos',
    events_url: 'https://api.github.com/users/austinbro5/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/austinbro5/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'AlyssaSaez',
    id: 47366310,
    node_id: 'MDQ6VXNlcjQ3MzY2MzEw',
    avatar_url: 'https://avatars2.githubusercontent.com/u/47366310?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/AlyssaSaez',
    html_url: 'https://github.com/AlyssaSaez',
    followers_url: 'https://api.github.com/users/AlyssaSaez/followers',
    following_url:
      'https://api.github.com/users/AlyssaSaez/following{/other_user}',
    gists_url: 'https://api.github.com/users/AlyssaSaez/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/AlyssaSaez/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/AlyssaSaez/subscriptions',
    organizations_url: 'https://api.github.com/users/AlyssaSaez/orgs',
    repos_url: 'https://api.github.com/users/AlyssaSaez/repos',
    events_url: 'https://api.github.com/users/AlyssaSaez/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/AlyssaSaez/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'Brimes7',
    id: 48000565,
    node_id: 'MDQ6VXNlcjQ4MDAwNTY1',
    avatar_url: 'https://avatars0.githubusercontent.com/u/48000565?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Brimes7',
    html_url: 'https://github.com/Brimes7',
    followers_url: 'https://api.github.com/users/Brimes7/followers',
    following_url:
      'https://api.github.com/users/Brimes7/following{/other_user}',
    gists_url: 'https://api.github.com/users/Brimes7/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Brimes7/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Brimes7/subscriptions',
    organizations_url: 'https://api.github.com/users/Brimes7/orgs',
    repos_url: 'https://api.github.com/users/Brimes7/repos',
    events_url: 'https://api.github.com/users/Brimes7/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Brimes7/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'PWalis',
    id: 48426713,
    node_id: 'MDQ6VXNlcjQ4NDI2NzEz',
    avatar_url: 'https://avatars2.githubusercontent.com/u/48426713?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/PWalis',
    html_url: 'https://github.com/PWalis',
    followers_url: 'https://api.github.com/users/PWalis/followers',
    following_url: 'https://api.github.com/users/PWalis/following{/other_user}',
    gists_url: 'https://api.github.com/users/PWalis/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/PWalis/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/PWalis/subscriptions',
    organizations_url: 'https://api.github.com/users/PWalis/orgs',
    repos_url: 'https://api.github.com/users/PWalis/repos',
    events_url: 'https://api.github.com/users/PWalis/events{/privacy}',
    received_events_url: 'https://api.github.com/users/PWalis/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'DKFerebee',
    id: 49910197,
    node_id: 'MDQ6VXNlcjQ5OTEwMTk3',
    avatar_url: 'https://avatars3.githubusercontent.com/u/49910197?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DKFerebee',
    html_url: 'https://github.com/DKFerebee',
    followers_url: 'https://api.github.com/users/DKFerebee/followers',
    following_url:
      'https://api.github.com/users/DKFerebee/following{/other_user}',
    gists_url: 'https://api.github.com/users/DKFerebee/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DKFerebee/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DKFerebee/subscriptions',
    organizations_url: 'https://api.github.com/users/DKFerebee/orgs',
    repos_url: 'https://api.github.com/users/DKFerebee/repos',
    events_url: 'https://api.github.com/users/DKFerebee/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DKFerebee/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'christopherc1331',
    id: 49927848,
    node_id: 'MDQ6VXNlcjQ5OTI3ODQ4',
    avatar_url: 'https://avatars3.githubusercontent.com/u/49927848?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/christopherc1331',
    html_url: 'https://github.com/christopherc1331',
    followers_url: 'https://api.github.com/users/christopherc1331/followers',
    following_url:
      'https://api.github.com/users/christopherc1331/following{/other_user}',
    gists_url: 'https://api.github.com/users/christopherc1331/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/christopherc1331/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/christopherc1331/subscriptions',
    organizations_url: 'https://api.github.com/users/christopherc1331/orgs',
    repos_url: 'https://api.github.com/users/christopherc1331/repos',
    events_url:
      'https://api.github.com/users/christopherc1331/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/christopherc1331/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
  {
    login: 'derekjpeters',
    id: 55850377,
    node_id: 'MDQ6VXNlcjU1ODUwMzc3',
    avatar_url: 'https://avatars0.githubusercontent.com/u/55850377?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/derekjpeters',
    html_url: 'https://github.com/derekjpeters',
    followers_url: 'https://api.github.com/users/derekjpeters/followers',
    following_url:
      'https://api.github.com/users/derekjpeters/following{/other_user}',
    gists_url: 'https://api.github.com/users/derekjpeters/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/derekjpeters/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/derekjpeters/subscriptions',
    organizations_url: 'https://api.github.com/users/derekjpeters/orgs',
    repos_url: 'https://api.github.com/users/derekjpeters/repos',
    events_url: 'https://api.github.com/users/derekjpeters/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/derekjpeters/received_events',
    type: 'User',
    site_admin: false,
    permissions: {
      admin: true,
      push: true,
      pull: true,
    },
  },
];
